generator:
  class: sfDoctrineGenerator
  param:
    model_class:           PublicationType
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          publication_type
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Publication Type List
        display: [=name]
        table_method: backendIndex
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
