generator:
  class: sfDoctrineGenerator
  param:
    model_class:           faculty
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          faculty
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display:
          - =last_name
          - =first_name
        table_method: backendIndex
      filter:
        display:
          - last_name
          - first_name
          - schools_list
      form:    ~
      edit:    ~
      new:     ~
