generator:
  class: sfDoctrineGenerator
  param:
    model_class:           school
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          school
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [=name]
        table_method: backendIndex
      filter:
        display: [name]
      form:    ~
      edit:    ~
      new:     ~
